version: 2

sources:
  - name: coffee_shop
    description: this is a replica of our postgres database. Loaded daily by hand
    project: analytics-engineers-club
    freshness:
      error_after:
        count: 12
        period: hour
    loaded_at_field: created_at
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null